const trails = [
  {
    id: "angels-landing",
    name: "Angels Landing",
    location: "Zion National Park, Utah",
    difficulty: "Hard",
    length: 5.4,
    elevationGain: 1488,
    estimatedTime: "4–5 hours",
    views: 5,
    tags: ["Chains", "Switchbacks", "Iconic"],
    description:
      "One of the most iconic hikes in the American Southwest, Angels Landing rewards brave hikers with jaw-dropping panoramic views of Zion Canyon. The final half-mile involves steep chains bolted into rock — not for the faint of heart.",
    tips: "Start before sunrise to beat the crowds and the heat. The chain section can be dangerous when wet — skip it after rain. Bring plenty of water and sunscreen; shade is scarce.",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
  },
  {
    id: "enchantments",
    name: "The Enchantments",
    location: "Leavenworth, Washington",
    difficulty: "Expert",
    length: 18.0,
    elevationGain: 4500,
    estimatedTime: "10–14 hours",
    views: 5,
    tags: ["Alpine Lakes", "Permit Required", "Epic"],
    description:
      "A breathtaking traverse through a high alpine basin dotted with crystal-clear lakes, granite peaks, and wild mountain goats. One of the most sought-after permits in the entire national forest system.",
    tips: "You need a permit — enter the lottery in February. Do this as a thru-hike from Snow Lakes to Colchuck Lake for the best experience. Bring layers; weather changes fast above 7,000 ft.",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
  },
  {
    id: "half-dome",
    name: "Half Dome",
    location: "Yosemite National Park, California",
    difficulty: "Hard",
    length: 14.2,
    elevationGain: 4800,
    estimatedTime: "10–12 hours",
    views: 5,
    tags: ["Cables", "Permit Required", "Legendary"],
    description:
      "Yosemite's crown jewel. The cables up the sheer granite face of Half Dome are a rite of passage for serious hikers. Views of Yosemite Valley from the top are absolutely unforgettable.",
    tips: "Permits are required for the cables section and sell out fast. Wear gloves for the cables — your hands will thank you. Start by 5am if you want to summit and return before afternoon thunderstorms.",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80",
  },
  {
    id: "appalachian-trail-section",
    name: "McAfee Knob",
    location: "Roanoke, Virginia",
    difficulty: "Moderate",
    length: 8.8,
    elevationGain: 1800,
    estimatedTime: "4–5 hours",
    views: 4,
    tags: ["Most Photographed", "Appalachian Trail", "Views"],
    description:
      "McAfee Knob is the most photographed spot on the entire Appalachian Trail — and for good reason. The rocky outcropping juts out over the Catawba Valley for an iconic 270-degree view.",
    tips: "Go on a weekday to avoid crowds. The overlook faces west, making it magical at sunset. Trail is well-marked and well-maintained — great for intermediate hikers.",
    image: "https://images.unsplash.com/photo-1587502537745-84b86da1204f?w=800&q=80",
  },
  {
    id: "narrows",
    name: "The Narrows",
    location: "Zion National Park, Utah",
    difficulty: "Moderate",
    length: 9.4,
    elevationGain: 334,
    estimatedTime: "4–8 hours",
    views: 5,
    tags: ["River Walk", "Slot Canyon", "Unique"],
    description:
      "Hike through the Virgin River itself, surrounded by towering sandstone walls that rise up to 1,000 feet. The Narrows is unlike any other hike — you'll wade and scramble through one of the most stunning slot canyons on Earth.",
    tips: "Rent neoprene socks and a walking stick from outfitters in Springdale — totally worth it. Check flash flood forecasts before going. Best done top-down with a shuttle if you can get a permit.",
    image: "https://images.unsplash.com/photo-1518623489648-a173ef7824f3?w=800&q=80",
  },
  {
    id: "bearfence-mountain",
    name: "Bearfence Mountain",
    location: "Shenandoah National Park, Virginia",
    difficulty: "Easy",
    length: 1.2,
    elevationGain: 175,
    estimatedTime: "45 min–1 hour",
    views: 4,
    tags: ["Short", "Scramble", "360° Views"],
    description:
      "Don't let the short distance fool you — Bearfence Mountain delivers one of the best 360-degree views in all of Shenandoah, and the short rock scramble to the top makes it an adventure for all ages.",
    tips: "Park at the Bearfence Mountain parking lot on Skyline Drive (mile 56.4). Wear sturdy shoes for the rock scramble. Perfect for families or anyone short on time.",
    image: "https://images.unsplash.com/photo-1476611338391-6f395a0dd82e?w=800&q=80",
  },
];

module.exports = trails;